name: Build

on: [push]

env:
  BUILD_TYPE: -r

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    

    - name: Build
      run: ./build.sh -r simulator

    - name: Test
      run:  ./tests_bin/run_tests.sh mesh
