name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install criterion
      run: |
        source ./scripts/actions/install_criterion.sh
        if [[ $? -eq 0 ]]; then
          echo "Criterion installed"
        fi
      shell: bash

    - name: Build without cuda
      run: ./build.sh -r simulator

    - name: Test without cuda
      run:  ./run_tests.sh

  build_ubuntu_latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build without cuda
      run: ./build.sh -r simulator

    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
        method: 'network'
        linux-local-args: '["--toolkit"]'

    - name: Build with cuda
      run: ./build.sh -r simulator
