name: Build

on: [push]

env:
  BUILD_TYPE: -r

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash      
      run: ls .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash      
      run:  ./tests_bin/run_tests.sh
