name: Build

on: [push]

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    

    - name: Install CUDA
      env:
        cuda: "11.0"
      run: |
        source ./scripts/actions/install_cuda_ubuntu.sh
        if [[ $? -eq 0 ]]; then
          # Set paths for subsequent steps, using ${CUDA_PATH}
          echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
          echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
          echo "CPATH=${CUDA_PATH}/targets/x86_64-linux/include:$CPATH" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build
      run: ./build.sh -r simulator

    - name: Test
      run:  ./tests_bin/run_tests.sh mesh
